import { Merchant, Product } from './types';

export const DEMO_MERCHANTS: Merchant[] = [
  {
    id: 'mer_croma_01',
    name: 'Croma Electronics',
    domain: 'croma.com',
    verified: true,
    trustScore: 98,
    rating: 4.8,
    activeSince: '2016',
    catalogCount: 1420,
    razorpayMerchantId: 'acc_rzp_croma_9918',
    returnPolicyDays: 14,
    location: 'Mumbai, India',
  },
  {
    id: 'mer_reliance_02',
    name: 'Reliance Digital Official',
    domain: 'reliancedigital.in',
    verified: true,
    trustScore: 96,
    rating: 4.7,
    activeSince: '2017',
    catalogCount: 2150,
    razorpayMerchantId: 'acc_rzp_reliance_4421',
    returnPolicyDays: 15,
    location: 'Bangalore, India',
  },
  {
    id: 'mer_vijay_03',
    name: 'Vijay Sales Express',
    domain: 'vijaysales.com',
    verified: true,
    trustScore: 94,
    rating: 4.6,
    activeSince: '2019',
    catalogCount: 880,
    razorpayMerchantId: 'acc_rzp_vijay_3310',
    returnPolicyDays: 10,
    location: 'Delhi, India',
  },
  {
    id: 'mer_sony_direct_04',
    name: 'Sony Center Direct',
    domain: 'sonycenter.in',
    verified: true,
    trustScore: 99,
    rating: 4.9,
    activeSince: '2015',
    catalogCount: 420,
    razorpayMerchantId: 'acc_rzp_sony_1029',
    returnPolicyDays: 30,
    location: 'Bengaluru, India',
  },
  {
    id: 'mer_unverified_99',
    name: 'QuickTech GrayMarket Warehouse',
    domain: 'quicktech-deals-now.xyz',
    verified: false,
    trustScore: 54,
    rating: 3.1,
    activeSince: '2024',
    catalogCount: 45,
    razorpayMerchantId: 'acc_rzp_unauth_0099',
    returnPolicyDays: 0,
    location: 'Unknown',
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod_sony_ch720n',
    name: 'Sony WH-CH720N Wireless Noise Canceling Headphones',
    brand: 'Sony',
    category: 'Wireless Headphones',
    price: 7999,
    shippingCost: 0,
    taxRate: 0, // Inclusive pricing for clean golden demo
    taxAmount: 0,
    stockQuantity: 42,
    merchantId: 'mer_sony_direct_04',
    merchant: DEMO_MERCHANTS[3],
    rating: 4.8,
    reviewsCount: 3410,
    specs: {
      driver: '30mm Integrated Processor V1',
      battery: '35 hours with ANC on',
      connectivity: 'Bluetooth 5.2, Multipoint',
      weight: '192g lightweight',
    },
    description: 'Dual Noise Sensor technology and Integrated Processor V1 take noise cancelling to the next level.',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 96,
    recommendationReason:
      'Best match because it satisfies the requested brand, remains within the authorized budget (₹7,999 <= ₹10,000) and is available from a verified merchant.',
    decisionFactors: [
      'Category matches "Wireless Headphones"',
      'Brand preference matches "Sony"',
      'Within authorized budget (₹7,999 <= ₹10,000)',
      'Merchant verified (Sony Center Direct, Trust: 99%)',
      'Product available in stock (42 units)',
      'Policy allows autonomous transaction below ₹10,000',
    ],
  },
  {
    id: 'prod_sony_xm5',
    name: 'Sony WH-1000XM5 Flagship Wireless ANC Headphones',
    brand: 'Sony',
    category: 'Wireless Headphones',
    price: 9499,
    shippingCost: 0,
    taxRate: 0,
    taxAmount: 0,
    stockQuantity: 18,
    merchantId: 'mer_croma_01',
    merchant: DEMO_MERCHANTS[0],
    rating: 4.9,
    reviewsCount: 9200,
    specs: {
      driver: '30mm carbon fiber composite',
      battery: '30 hours',
      connectivity: 'Bluetooth 5.2, LDAC, Hi-Res',
      weight: '250g',
    },
    description: 'Industry leading noise cancellation with two processors and 8 microphones.',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 91,
    recommendationReason:
      'Premium alternative within budget. High rating (4.9) and verified merchant with 14-day replacement guarantee.',
    decisionFactors: [
      'Category matches "Wireless Headphones"',
      'Brand matches "Sony"',
      'Within budget boundary (₹9,499 <= ₹10,000)',
      'Merchant verified (Croma Electronics)',
      'Product available in stock (18 units)',
    ],
  },
  {
    id: 'prod_bose_qc',
    name: 'Bose QuietComfort Wireless Headphones',
    brand: 'Bose',
    category: 'Wireless Headphones',
    price: 8799,
    shippingCost: 0,
    taxRate: 0,
    taxAmount: 0,
    stockQuantity: 12,
    merchantId: 'mer_reliance_02',
    merchant: DEMO_MERCHANTS[1],
    rating: 4.7,
    reviewsCount: 2840,
    specs: {
      modes: 'Quiet and Aware modes',
      battery: '24 hours',
      connectivity: 'Bluetooth 5.1',
      weight: '240g',
    },
    description: 'Legendary noise cancellation, comfortable over-ear fit, and adjustable EQ modes.',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 84,
    recommendationReason:
      'Top-tier comfort and ANC, though brand differs from requested preference "Sony". Fully within authorized spending boundary.',
    decisionFactors: [
      'Category matches "Wireless Headphones"',
      'Alternative brand "Bose"',
      'Within budget boundary (₹8,799 <= ₹10,000)',
      'Merchant verified (Reliance Digital Official)',
      'Product available in stock',
    ],
  },
  {
    id: 'prod_jbl_live770',
    name: 'JBL Live 770NC Wireless Over-Ear Headphones',
    brand: 'JBL',
    category: 'Wireless Headphones',
    price: 6999,
    shippingCost: 0,
    taxRate: 0,
    taxAmount: 0,
    stockQuantity: 28,
    merchantId: 'mer_vijay_03',
    merchant: DEMO_MERCHANTS[2],
    rating: 4.5,
    reviewsCount: 1450,
    specs: {
      sound: 'JBL Signature Sound with Personi-Fi 2.0',
      battery: '65 hours (50h with BT+NC)',
      connectivity: 'Bluetooth 5.3',
    },
    description: 'True Adaptive Noise Cancelling with Smart Ambient, immersive JBL Spatial Sound.',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 78,
    recommendationReason:
      'Value option under ₹7,000 with exceptional battery life (65h). Fully compatible with autonomous limit.',
    decisionFactors: [
      'Category matches "Wireless Headphones"',
      'Alternative brand "JBL"',
      'Significantly under budget (₹6,999 vs ₹10,000)',
      'Merchant verified (Vijay Sales Express)',
    ],
  },
  {
    id: 'prod_budget_violation_sample',
    name: 'Sony WH-1000XM5 Studio Edition + Gold Audio Interface Bundle',
    brand: 'Sony',
    category: 'Wireless Headphones',
    price: 9499,
    shippingCost: 500,
    taxRate: 0.18,
    taxAmount: 1209, // Total = 9499 + 500 + 1209 = 11,208!
    stockQuantity: 5,
    merchantId: 'mer_croma_01',
    merchant: DEMO_MERCHANTS[0],
    rating: 4.9,
    reviewsCount: 420,
    specs: {
      bundle: 'Headphones + Hi-Res DAC Interface + Studio Stand',
      taxBreakdown: '18% GST (₹1,209) + Express Freight (₹500)',
    },
    description: 'Pro bundle with ancillary fees resulting in ₹11,208 payable, exceeding ₹10,000 authorized ceiling.',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 88,
    recommendationReason:
      'Violates budget boundary. Final payable ₹11,208 exceeds user authorized spending ceiling of ₹10,000 by ₹1,208.',
    decisionFactors: [
      'Category matches "Wireless Headphones"',
      'Brand matches "Sony"',
      'CRITICAL: Final payable ₹11,208 exceeds authorized ceiling of ₹10,000',
      'Transaction Guard will deterministically BLOCK payment initiation',
    ],
  },
  {
    id: 'prod_drift_violation_sample',
    name: 'Sony WH-1000XM5 Executive Edition Platinum',
    brand: 'Sony',
    category: 'Wireless Headphones',
    price: 11999,
    shippingCost: 0,
    taxRate: 0,
    taxAmount: 0,
    stockQuantity: 8,
    merchantId: 'mer_croma_01',
    merchant: DEMO_MERCHANTS[0],
    rating: 4.9,
    reviewsCount: 310,
    specs: {
      edition: 'Limited Platinum finish, 2-year extended warranty',
    },
    description: 'Designed for intent drift testing. User intent: max ₹8,000 -> Selected: ₹11,999 (+₹3,999 drift).',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 65,
    recommendationReason:
      'Intent drift detected: Selected product is ₹11,999 against original user intent ceiling of ₹8,000 (+₹3,999 drift).',
    decisionFactors: [
      'Category matches "Wireless Headphones"',
      'Brand matches "Sony"',
      'INTENT DRIFT: Requested ₹8,000 vs Final ₹11,999 (+₹3,999)',
      'Transaction Guard will BLOCK due to unauthorized budget drift',
    ],
  },
  {
    id: 'prod_human_approval_sample',
    name: 'Sony Alpha FX30 Cinema Line Creator Camera Rig',
    brand: 'Sony',
    category: 'Digital Imaging',
    price: 38000,
    shippingCost: 0,
    taxRate: 0,
    taxAmount: 0,
    stockQuantity: 4,
    merchantId: 'mer_sony_direct_04',
    merchant: DEMO_MERCHANTS[3],
    rating: 4.9,
    reviewsCount: 180,
    specs: {
      sensor: 'APS-C 26.1MP Exmor R CMOS 4K 120p',
      authorization: 'Exceeds autonomous limit (₹38,000 > ₹10,000)',
    },
    description: 'High-value transaction test product. Final amount is ₹38,000 requiring explicit Human Authorization.',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 94,
    recommendationReason:
      'High-tier pro equipment requested. Transaction amount (₹38,000) exceeds autonomous boundary (₹10,000). Escalates to Human Approval.',
    decisionFactors: [
      'High-value asset (₹38,000)',
      'Autonomous policy limit is ₹10,000',
      'Requires explicit Human Gatekeeper signature before payment dispatch',
    ],
  },
  {
    id: 'prod_running_shoes',
    name: 'Nike Air Zoom Pegasus 40 Road Running Shoes',
    brand: 'Nike',
    category: 'Footwear',
    price: 7499,
    shippingCost: 0,
    taxRate: 0,
    taxAmount: 0,
    stockQuantity: 34,
    merchantId: 'mer_reliance_02',
    merchant: DEMO_MERCHANTS[1],
    rating: 4.7,
    reviewsCount: 890,
    specs: {
      cushioning: 'React foam with dual Zoom Air units',
      surface: 'Road / Asphalt',
    },
    description: 'Responsive daily training shoe built for smooth energy return.',
    aiReady: true,
    purchaseEnabled: true,
    aiMatchScore: 95,
    recommendationReason: 'Best match for running shoes query under ₹8,000.',
    decisionFactors: [
      'Category matches "Footwear / Running Shoes"',
      'Price ₹7,499 is within user budget ₹8,000',
      'Merchant verified',
    ],
  },
  {
    id: 'prod_unverified_trap',
    name: 'Sony WH-1000XM4 Refurbished Discount Special',
    brand: 'Sony',
    category: 'Wireless Headphones',
    price: 7500,
    shippingCost: 0,
    taxRate: 0,
    taxAmount: 0,
    stockQuantity: 10,
    merchantId: 'mer_unverified_99',
    merchant: DEMO_MERCHANTS[4], // Unverified!
    rating: 3.2,
    reviewsCount: 14,
    specs: {
      origin: 'Unverified gray market stock',
    },
    description: 'Test product from unverified merchant to test Policy Gate Merchant Verification.',
    aiReady: false,
    purchaseEnabled: true,
    aiMatchScore: 50,
    recommendationReason: 'Merchant not verified. Will fail deterministic Merchant Verification check.',
    decisionFactors: [
      'WARNING: Merchant "QuickTech GrayMarket Warehouse" is unverified',
      'Policy mandates verified merchants only',
    ],
  },
];
