/**
 * Standalone seed transactions for use by firestoreService bootstrap.
 * Extracted from RazorGateContext so Firestore service can import without circular deps.
 */
import type { Transaction } from './types';
import { DEMO_PRODUCTS } from './merchantsAndCatalog';

export const SEED_TRANSACTIONS: Transaction[] = [
  // 1. Sony WH-CH720N (Approved, ₹7,999)
  {
    id: 'tx_rzg_001',
    intent: {
      rawPrompt: 'Find Sony wireless headphones under ₹10,000',
      category: 'Wireless Headphones',
      maxBudget: 10000,
      preferredBrand: 'Sony',
      quantity: 1,
      merchantRequirement: 'verified_only',
      paymentAuthorization: 'autonomous_below_budget',
      confidenceScore: 0.98,
      parsedTimestamp: new Date(Date.now() - 120000).toISOString(),
    },
    product: DEMO_PRODUCTS[0],
    unitPrice: 7999,
    quantity: 1,
    shippingAmount: 0,
    taxAmount: 0,
    finalPayable: 7999,
    authorizedMaximum: 10000,
    autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Category and brand match user request', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Sony Center Direct is verified (Trust: 99%)', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: '42 units available in stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: '₹7,999 is within authorized limit of ₹10,000', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Category authorized under policy and within daily budget', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Amount is within autonomous limit of ₹10,000', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'APPROVED',
    decisionReason: 'All deterministic policy and boundary checks passed.',
    decisionFactors: DEMO_PRODUCTS[0].decisionFactors || [],
    paymentStatus: 'SUCCESS',
    paymentId: 'pay_rzp_demo_auth_7819',
    razorpayOrderId: 'order_rzp_seed_9801',
    razorpaySignature: 'sig_rzp_mock_verified_001',
    createdAt: new Date(Date.now() - 120000).toISOString(),
    updatedAt: new Date(Date.now() - 110000).toISOString(),
    executionMode: 'DEMO_SIMULATED',
  },

  // 2. JBL Live 770NC (Approved, ₹6,999) → 7,999 + 6,999 = ₹14,998!
  {
    id: 'tx_rzg_002',
    intent: {
      rawPrompt: 'Get noise cancelling headphones under ₹8,000',
      category: 'Wireless Headphones',
      maxBudget: 8000,
      preferredBrand: 'JBL',
      quantity: 1,
      merchantRequirement: 'verified_only',
      paymentAuthorization: 'autonomous_below_budget',
      confidenceScore: 0.96,
      parsedTimestamp: new Date(Date.now() - 3600000).toISOString(),
    },
    product: DEMO_PRODUCTS[3],
    unitPrice: 6999,
    quantity: 1,
    shippingAmount: 0,
    taxAmount: 0,
    finalPayable: 6999,
    authorizedMaximum: 8000,
    autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Matches category "Wireless Headphones"', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Vijay Sales Express verified', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: '28 units available', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: '₹6,999 <= ₹8,000 authorized', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Category and daily limit approved', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Autonomous authorization valid', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'APPROVED',
    decisionReason: 'All deterministic policy and boundary checks passed.',
    decisionFactors: DEMO_PRODUCTS[3].decisionFactors || [],
    paymentStatus: 'SUCCESS',
    paymentId: 'pay_rzp_demo_auth_7820',
    razorpayOrderId: 'order_rzp_seed_9802',
    razorpaySignature: 'sig_rzp_mock_verified_002',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3590000).toISOString(),
    executionMode: 'DEMO_SIMULATED',
  },

  // 3–7: Zero-cost accessories (approved, ₹0 each — keep benchmark at ₹14,998)
  {
    id: 'tx_rzg_003',
    intent: { rawPrompt: 'Replacement silicone ear cushions warranty claim', category: 'Wireless Headphones', maxBudget: 1000, quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.99, parsedTimestamp: new Date(Date.now() - 7200000).toISOString() },
    product: { ...DEMO_PRODUCTS[0], id: 'prod_acc_01', name: 'Sony Official Silicone Replacement Cushions (Warranty)', price: 0, shippingCost: 0, taxAmount: 0 },
    unitPrice: 0, quantity: 1, shippingAmount: 0, taxAmount: 0, finalPayable: 0, authorizedMaximum: 1000, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Warranty SKU match', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Sony Center Direct verified', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'Available in service stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: '₹0 within budget', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Approved under warranty policy', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Autonomous settlement', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'APPROVED', decisionReason: 'All checks passed.', decisionFactors: ['Approved warranty SKU'],
    paymentStatus: 'SUCCESS', paymentId: 'pay_rzp_demo_auth_7821',
    createdAt: new Date(Date.now() - 7200000).toISOString(), updatedAt: new Date(Date.now() - 7190000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },
  {
    id: 'tx_rzg_004',
    intent: { rawPrompt: 'Audio cable accessory fulfillment', category: 'Audio Equipment', maxBudget: 500, quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.98, parsedTimestamp: new Date(Date.now() - 10800000).toISOString() },
    product: { ...DEMO_PRODUCTS[0], id: 'prod_acc_02', name: 'Gold-Plated 3.5mm Braided Audio Cable (Rebate)', price: 0, shippingCost: 0, taxAmount: 0 },
    unitPrice: 0, quantity: 1, shippingAmount: 0, taxAmount: 0, finalPayable: 0, authorizedMaximum: 500, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Matches accessory intent', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Verified merchant', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'In stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: '₹0 within budget', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Policy approved', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Autonomous approved', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'APPROVED', decisionReason: 'All checks passed.', decisionFactors: ['Approved loyalty perk SKU'],
    paymentStatus: 'SUCCESS', paymentId: 'pay_rzp_demo_auth_7822',
    createdAt: new Date(Date.now() - 10800000).toISOString(), updatedAt: new Date(Date.now() - 10790000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },
  {
    id: 'tx_rzg_005',
    intent: { rawPrompt: 'Protective carrying pouch', category: 'Wireless Headphones', maxBudget: 600, quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.97, parsedTimestamp: new Date(Date.now() - 14400000).toISOString() },
    product: { ...DEMO_PRODUCTS[0], id: 'prod_acc_03', name: 'Protective Hard Shell Travel Case', price: 0, shippingCost: 0, taxAmount: 0 },
    unitPrice: 0, quantity: 1, shippingAmount: 0, taxAmount: 0, finalPayable: 0, authorizedMaximum: 600, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Matches travel case', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Verified', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'In stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: 'Within budget', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Approved', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Autonomous approved', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'APPROVED', decisionReason: 'All checks passed.', decisionFactors: ['Approved accessory'],
    paymentStatus: 'SUCCESS', paymentId: 'pay_rzp_demo_auth_7823',
    createdAt: new Date(Date.now() - 14400000).toISOString(), updatedAt: new Date(Date.now() - 14390000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },
  {
    id: 'tx_rzg_006',
    intent: { rawPrompt: 'USB-C fast charging cable', category: 'Electronics', maxBudget: 400, quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.99, parsedTimestamp: new Date(Date.now() - 18000000).toISOString() },
    product: { ...DEMO_PRODUCTS[0], id: 'prod_acc_04', name: 'USB-C Fast Charging Data Cable (Certified)', price: 0, shippingCost: 0, taxAmount: 0 },
    unitPrice: 0, quantity: 1, shippingAmount: 0, taxAmount: 0, finalPayable: 0, authorizedMaximum: 400, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Matches cable intent', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Verified merchant', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'In stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: 'Within budget', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Approved', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Autonomous approved', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'APPROVED', decisionReason: 'All checks passed.', decisionFactors: ['Approved cable SKU'],
    paymentStatus: 'SUCCESS', paymentId: 'pay_rzp_demo_auth_7824',
    createdAt: new Date(Date.now() - 18000000).toISOString(), updatedAt: new Date(Date.now() - 17990000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },
  {
    id: 'tx_rzg_007',
    intent: { rawPrompt: 'Precision electronics cleaning cloth', category: 'Electronics', maxBudget: 300, quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.98, parsedTimestamp: new Date(Date.now() - 21600000).toISOString() },
    product: { ...DEMO_PRODUCTS[0], id: 'prod_acc_05', name: 'Anti-Static Microfiber Cleaning Cloth', price: 0, shippingCost: 0, taxAmount: 0 },
    unitPrice: 0, quantity: 1, shippingAmount: 0, taxAmount: 0, finalPayable: 0, authorizedMaximum: 300, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Matches cleaning kit', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Verified merchant', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'In stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: 'Within budget', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Approved', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Autonomous approved', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'APPROVED', decisionReason: 'All checks passed.', decisionFactors: ['Approved maintenance SKU'],
    paymentStatus: 'SUCCESS', paymentId: 'pay_rzp_demo_auth_7825',
    createdAt: new Date(Date.now() - 21600000).toISOString(), updatedAt: new Date(Date.now() - 21590000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },

  // 8. Blocked: Sony WH-1000XM5 Executive Edition (₹11,999 vs ₹10,000 limit)
  {
    id: 'tx_rzg_008',
    intent: { rawPrompt: 'Buy headphones under ₹10,000', category: 'Wireless Headphones', maxBudget: 10000, preferredBrand: 'Sony', quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.94, parsedTimestamp: new Date(Date.now() - 1080000).toISOString() },
    product: DEMO_PRODUCTS[5],
    unitPrice: 11999, quantity: 1, shippingAmount: 0, taxAmount: 0, finalPayable: 11999, authorizedMaximum: 10000, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Category matches', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Croma Electronics verified', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'In stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'FAIL', detail: '₹11,999 exceeds authorized ceiling ₹10,000 by ₹1,999', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Category permitted', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'REVIEW', detail: 'Exceeds autonomous limit', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'BLOCKED', decisionReason: "Transaction exceeds the user's autonomous authorization limit.",
    decisionFactors: ['CRITICAL: Exceeds authorized spending boundary of ₹10,000'],
    intentDrift: { detected: true, originalBudget: 10000, finalPayable: 11999, difference: 1999, percentageDrift: 20, driftType: 'BUDGET_OVERRUN', explanation: 'Final amount (₹11,999) exceeds intent (₹10,000) by +₹1,999 (+20%)' },
    paymentStatus: 'BLOCKED_PRE_PAYMENT',
    createdAt: new Date(Date.now() - 1080000).toISOString(), updatedAt: new Date(Date.now() - 1080000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },

  // 9. Blocked: Studio Bundle (₹11,208 — fee escalation)
  {
    id: 'tx_rzg_009',
    intent: { rawPrompt: 'Find Sony headphones under ₹10,000', category: 'Wireless Headphones', maxBudget: 10000, preferredBrand: 'Sony', quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.95, parsedTimestamp: new Date(Date.now() - 28800000).toISOString() },
    product: DEMO_PRODUCTS[4],
    unitPrice: 9499, quantity: 1, shippingAmount: 500, taxAmount: 1209, finalPayable: 11208, authorizedMaximum: 10000, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Category matches', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'PASS', detail: 'Croma Electronics verified', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'In stock', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'FAIL', detail: 'Final payable ₹11,208 exceeds authorized ceiling ₹10,000', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Category authorized under policy', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'REVIEW', detail: 'Exceeds autonomous limit', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'BLOCKED', decisionReason: 'Final payable exceeds authorized spending boundary.',
    decisionFactors: ['Fee escalation: GST + Freight pushed final to ₹11,208'],
    paymentStatus: 'BLOCKED_PRE_PAYMENT',
    createdAt: new Date(Date.now() - 28800000).toISOString(), updatedAt: new Date(Date.now() - 28800000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },

  // 10. Blocked: Gray Market Unverified Seller
  {
    id: 'tx_rzg_010',
    intent: { rawPrompt: 'Find cheapest Sony headphones', category: 'Wireless Headphones', maxBudget: 10000, preferredBrand: 'Sony', quantity: 1, merchantRequirement: 'verified_only', paymentAuthorization: 'autonomous_below_budget', confidenceScore: 0.93, parsedTimestamp: new Date(Date.now() - 32400000).toISOString() },
    product: DEMO_PRODUCTS[8],
    unitPrice: 7500, quantity: 1, shippingAmount: 0, taxAmount: 0, finalPayable: 7500, authorizedMaximum: 10000, autonomousLimit: 10000,
    checks: [
      { id: 'c1', checkName: 'Intent Match', status: 'PASS', detail: 'Category matches', ruleApplied: 'INTENT_CATEGORY_BRAND_ALIGNMENT' },
      { id: 'c2', checkName: 'Merchant Verification', status: 'FAIL', detail: 'Merchant "QuickTech GrayMarket Warehouse" is unverified. Policy prohibits unverified merchant settlement.', ruleApplied: 'POLICY_VERIFIED_MERCHANT_MANDATE' },
      { id: 'c3', checkName: 'Product Availability', status: 'PASS', detail: 'Available', ruleApplied: 'INVENTORY_RESERVATION_VALID' },
      { id: 'c4', checkName: 'Budget Boundary', status: 'PASS', detail: 'Within budget', ruleApplied: 'USER_BUDGET_CEILING_ENFORCEMENT' },
      { id: 'c5', checkName: 'Policy', status: 'PASS', detail: 'Category allowed', ruleApplied: 'ENTERPRISE_COMMERCE_POLICY_RULES' },
      { id: 'c6', checkName: 'Payment Authorization', status: 'PASS', detail: 'Within autonomous limit', ruleApplied: 'AUTONOMOUS_LIMIT_GOVERNANCE' },
    ],
    decision: 'BLOCKED', decisionReason: 'Merchant is unverified. Policy mandates verified merchants only.',
    decisionFactors: ['Merchant Verification FAILED: unverified gray-market seller'],
    paymentStatus: 'BLOCKED_PRE_PAYMENT',
    createdAt: new Date(Date.now() - 32400000).toISOString(), updatedAt: new Date(Date.now() - 32400000).toISOString(), executionMode: 'DEMO_SIMULATED',
  },
];
